// @ts-nocheck
import { getApiKey } from './client';

const IMAGEN_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict';

export interface GenerateImageOptions {
  prompt: string;
  aspectRatio?: string;
  numberOfImages?: number;
  tenantId?: string;
}

export interface GeneratedImage {
  base64: string;
  mimeType: string;
}

export async function generateImage(options: GenerateImageOptions): Promise<GeneratedImage> {
  const { prompt, aspectRatio = '1:1', numberOfImages = 1, tenantId } = options;

  const apiKey = await getApiKey(tenantId);

  const response = await fetch(IMAGEN_API_URL, {
    method: 'POST',
    headers: {
      'x-goog-api-key': apiKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      instances: [{ prompt }],
      parameters: {
        sampleCount: numberOfImages,
        aspectRatio,
      },
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Imagen API error: ${response.status} - ${error}`);
  }

  const data = await response.json();

  if (!data.predictions || data.predictions.length === 0) {
    throw new Error('No images generated by Imagen API');
  }

  const prediction = data.predictions[0];

  return {
    base64: prediction.bytesBase64Encoded,
    mimeType: prediction.mimeType || 'image/png',
  };
}
